### ISSUE TITLE
Missing doc for specifying Terraform input variable type

### ISSUE THREAD

**Issue by stevestrutt** [ibm-cloud-docs/schematics#10]
Schematics docs do not identify the need for Terraform input variables to have a type definition for the type to be correctly show in the input variables UI and for the UI to correctly process override variables. 

There are multiple Schematics and UI defects in this area, where the default type is shown incorrectly and Schematics does not honour the type specified by the user. However Terraform is able to process these definitions correctly without error. The issues are in the UI and API. 
Issue https://github.ibm.com/blueprint/product/issues/2023 
https://github.ibm.com/alchemy-containers/schematics-ui/issues/582
https://github.ibm.com/alchemy-containers/schematics-ui/issues/581

When these issues are resolved the docs need updating to reflect the requirement that users have to specify the variable type when they import existing working Terraform templates into Schematics. 

The section:
https://cloud.ibm.com/docs/schematics?topic=schematics-create-tf-config under https://cloud.ibm.com/docs/schematics?topic=schematics-create-tf-config#configure-variables requires updating with the need to specify a type. 

Overall the Schematics documentation has no reference to override values and the use of variable types.. This is also relevant to the docs on ValueSets (Presets).  Likely under the Creating Workspaces section. 

Variable of  
```
variable "frontend_hosts" {
  type        = list(list(string))
  description = "List of private IP addresses of target hosts"
  default     = [["host1", "172.16.2.12"], ["host2", "172.16.2.13"]]
}
```

**Comment by Nadine2016** [comment]
added to the documentation that declaring a data type is required. also updated the examples to show a type. closing this issue. information will be pushed out to prod today
