### ISSUE TITLE
Whatsnew should mention the use of Terraform 0.13

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/schematics#13]
The [What's new](https://cloud.ibm.com/docs/schematics?topic=schematics-new-in-schematics) page should mention
the announcement of this blog including support for Terraform 0.13

https://www.ibm.com/cloud/blog/announcements/ibm-cloud-terraform-provider-updates-and-closed-beta-of-ansible-actions-in-schematics

**Comment by geethasathyamurthy** [comment]
@lionelmace,

Thanks for letting us know this. Terraform v0.13 support is shared in what's new in November https://cloud.ibm.com/docs/schematics?topic=schematics-new-in-schematics#november-2020 . However, we have included the blog link in our beta release February what's new https://cloud.ibm.com/docs/schematics?topic=schematics-new-in-schematics#February-2021.

Regards,
Geetha
