### ISSUE TITLE
Example which references .template_id from ibm.schematics_workspace doesn't work

### ISSUE THREAD

**Issue by ileneruth** [ibm-cloud-docs/schematics#15]
The remotestate.tf example has the following: 

```
data "ibm_schematics_output" "vpc" {
     workspace_id = "<schematics_workspace_ID>"
     template_id  = data.ibm_schematics_workspace.vpc.template_id.0
 }
```

However, when I try this, it fails, saying that there's no template_attribute on the workspace.

Examining the terraform attributes described here: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/schematics_workspace

I found that I had to replace

     template_id  = data.ibm_schematics_workspace.vpc.template_id.0

with 

    template_id = data.ibm_schematics_workspace.vpc.runtime_data.0.id

to get it to work. 

Note that this also affects the documentation for ibm_schematics_output on registry.terraform.io which is not aligned with the actual available attributes.

**Comment by geethasathyamurthy** [comment]
@ileneruth 

Thanks much for sharing the observation, we have updated in the documentation. Here is the updated link https://cloud.ibm.com/docs/schematics?topic=schematics-remote-state.

Request to close the issue, if the edit is good.

Thanks,
Geetha

**Comment by ileneruth** [comment]
Looks good now, thanks.
