### ISSUE TITLE
Link leads to dead end

### ISSUE THREAD

**Issue by Corrisoner** [ibm-cloud-docs/schematics#18]
The sections of Schematics Workspaces (https://cloud.ibm.com/docs/schematics?topic=schematics-learn-about-schematics#sch-workspaces) references a dead link:

Schematics Workspaces
With Schematics Workspaces, use Terraform to automate the [provisioning and configuration management](https://cloud.ibm.com/docs/schematics?topic=schematics-schematics-open-projects) of your IBM Cloud resources, and rapidly build, duplicate, and scale complex, multitiered cloud environments. For more information, see [Schematics Workspaces](https://cloud.ibm.com/docs/schematics?topic=schematics-sch-workspaces).

The last link (https://cloud.ibm.com/docs/schematics?topic=schematics-sch-workspaces) is leading to a dead end.

**Comment by geethasm** [comment]
@Corrisoner 

This is fixed, sorry for the delay in the reply. There was a major edits in the documentation during 2023, hence this dead link would have been present. 

https://cloud.ibm.com/docs/schematics?topic=schematics-learn-about-schematics#sch-workspaces


Now, it is fixed, request to confirm and close the issue.

Thanks much for bringing to our notice.

Geetha

**Comment by geethasathyamurthy** [comment]
@Corrisoner 
Closing this issue as it is fixed. Thanks!!
