### ISSUE TITLE
Comment about Terraform v1.6.x in the deprecation documentation needed

### ISSUE THREAD

**Issue by jarrodu** [ibm-cloud-docs/schematics#20]
Terraform has a new version. The documentation does not mention it.

I am interested in knowing if and when Terraform v1.6.x will be supported by Schematics.

In the [documentation](https://github.com/ibm-cloud-docs/schematics/blob/7420bb9915a9a9bd32c527aa72f5952e2b18b9f5/deprecation-tf.md), it says that v1.5.x will be at the "end of maintenance and security support" by the end of December 2023.

Could the table please be updated with information about v1.6.x?

**Comment by jarrodu** [comment]
December is getting closer and closer by the day.

Any update on this topic?

**Comment by jarrodu** [comment]
It is January now. Any idea what the future of Terraform on IBM will be?

**Comment by geethasm** [comment]
@jarrodu 

Thanks for using the Schematics, and sharing the input.

The team is in the process of implementing the depreciation details, shortly you will see the comment about depreciation details of Terraform version in the schematics UI and docs.

Regards,
Geetha

**Comment by jarrodu** [comment]
https://www.forbes.com/sites/stevemcdowell/2024/04/24/ibm-bolsters-hybrid-cloud-business-with-64b-hashicorp-acquisition/

Everything makes sense now. 🤣

**Comment by geethasathyamurthy** [comment]
Hi @jarrodu 

The Terraform deprecation and usage version details are published in the [docs](https://cloud.ibm.com/docs/schematics?topic=schematics-deprecate-tf-version). Hence we are closing this issue, request to reopen the issue.

Thanks,
Geetha
