### ISSUE TITLE
ansible fetch and copy. 

### ISSUE THREAD

**Issue by doyoungim999** [ibm-cloud-docs/schematics#21]
Hello, 
I am looking for some documentation about temporary storage in schematics actions. 
I cannot find any documentation. 

I failed with the location:  "/tmp/.schematics/" . 
Anyone can help about this? 
I think ansible copy is one of the common action.

**Comment by geethasm** [comment]
@doyoungim999 

Sorry for the delay in reply, You are right, Ansible copy is one of the common action, here is the [documentation link](https://cloud.ibm.com/docs/schematics?topic=schematics-general-faq#clone-file-extension).

**Comment by geethasathyamurthy** [comment]
Hi @doyoungim999 

Closing this issue, as here are the list of Ansible related docs

- [Files removed or missing from Terraform, or Ansible template repos](https://cloud.ibm.com/docs/schematics?topic=schematics-general-faq#clone-file-extension)
- [Fetching an action](https://cloud.ibm.com/docs/schematics?topic=schematics-action-working#action-settings) 
- [Creating Ansible roles and galaxy](https://cloud.ibm.com/docs/schematics?topic=schematics-ansible-roles-galaxy)
