### ISSUE TITLE
Confusing docs on providing vars in files

### ISSUE THREAD

**Issue by kemarsh** [ibm-cloud-docs/schematics#22]
Confusing examples on https://cloud.ibm.com/docs/schematics?topic=schematics-create-tf-config#configure-variables

In the example of `list(object)` I'm assuming the `<\br>` tags shouldn't be present in the object type definition shown.

In the example of `list(list(string))` it appears to show a list of objects.

![image](https://github.com/ibm-cloud-docs/schematics/assets/27019868/a9f7862a-7f5a-476a-b966-829705e6df97)

**Comment by geethasathyamurthy** [comment]
@kemarsh 

This is fixed and [published](https://test.cloud.ibm.com/docs/schematics?topic=schematics-create-tf-config#configure-variables) here. Request to confirm the same to close the issue. 

Thanks,

**Comment by kemarsh** [comment]
@geethasathyamurthy I don't see any obvious difference in the doc you linked to. Can you describe what was changed?

**Comment by geethasathyamurthy** [comment]
@kemarsh Here are the edits, request to confirm the fix to close the issue. Thanks!!

https://cloud.ibm.com/docs/schematics?topic=schematics-create-tf-config#configure-variables
<img width="753" alt="Screenshot 2024-08-01 at 12 53 20 PM" src="https://github.com/user-attachments/assets/03e53c10-f7f7-4b92-bef6-9dfb7635117e">

List of Strings

<img width="754" alt="Screenshot 2024-08-01 at 12 53 44 PM" src="https://github.com/user-attachments/assets/643c3d62-282f-4631-91ae-1ecb9fc8e896">

**Comment by kemarsh** [comment]
@geethasathyamurthy looks good to me - thanks for making the fix.

**Comment by geemurth** [comment]
Thanks for the confirmation, @kemarsh , we will close the issue.
