### ISSUE TITLE
Soon to be depreciated link

### ISSUE THREAD

**Issue by psschwei** [ibm-cloud-docs/schematics#8]
In the "Benefits / Use native Terraform capabilities" section, the link to the "IBM Cloud Provider for Terraform" documentation is being depreciated per a notice at the top of the page. The new link is : https://cloud.ibm.com/docs/terraform?topic=terraform-tf-provider

**Comment by Nadine2016** [comment]
@psschwei thank you. I updated the link and will push out this change today. closing this issue.
